# main text of home
name: Antoine Froger
bio: 'Senior Backend Software Engineer'

# if it's an external image, update below for true
external-image: true
picture: 'https://avatars2.githubusercontent.com/u/3509631'

url: ''

markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

analytics-google: 'UA-60532987-4'

# social networks
twitter: __tooni__
linkedin: antoinefroger
github: antfroger

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# navigation
about: true
resume: true
resume_url: '/docs/resume-antoine-froger.pdf'

# projects
projects: []

# talks
talks: [
    {
        title: "Be SOLID",
        description: "Tech meetup @ Newcraft",
        url: "/slides-be-solid"
    },
    {
        title: "Git (survival kit)",
        description: "Workshop @ Etsy France / A little Market",
        url: "/slides-git-survival-kit"
    }
]

# posts
blog_posts: [
    {
        date: "2016/07/27",
        title: "How Etsy France migrated all its sites to HTTPS",
        url: "http://codepaperscissors.com/projects/2016/07/27/https-securise-websites/"
    },
    {
        date: "2015/04/03",
        title: "The technical workflow at Etsy France (Part 1)",
        url: "http://codepaperscissors.com/workflow/2015/04/03/technical-workflow/"
    }
]

# do you want some animations?
animation: true

exclude: [README.md, _site, CNAME, Vagrantfile, provision]
